# Machine Learning Lab — Module 1
## Introduction to ML & Linear Algebra

### Lab focus
1. Matrix addition, multiplication, and transpose using NumPy
2. Eigenvalues and eigenvectors of a 2×2 matrix using NumPy

**Learning goal:** Build the linear-algebra skills needed for later ML topics such as PCA and regression.

## 1. Required Library

We will use **NumPy** for numerical and matrix operations.

In [106]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

## 2. Create Matrices

A matrix can be represented in NumPy using a 2-D array.

Example:

$
A = \begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}
$

In [125]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("A =\n", A)
print("\nB =\n", B)

A =
 [[1 2]
 [3 4]]

B =
 [[5 6]
 [7 8]]


## 3. Matrix Addition

Matrix addition is performed element-by-element:

$
A+B =
\begin{bmatrix}
a_{11}+b_{11} & a_{12}+b_{12} \\
a_{21}+b_{21} & a_{22}+b_{22}
\end{bmatrix}
$

In NumPy, use `A + B`.

In [128]:
C = A + B

print("A + B =\n", C)

A + B =
 [[ 6  8]
 [10 12]]


### Practice

Create two 3×3 matrices and calculate their sum.

In [131]:
# TODO: Create two 3x3 matrices and add them
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

N = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print(M + N)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


## 4. Matrix Multiplication

For matrix multiplication, the number of columns of the first matrix must equal the number of rows of the second matrix.

Use:

```python
A @ B
```

or:

```python
np.matmul(A, B)
```

**Important:** `A * B` performs element-wise multiplication, not matrix multiplication.

In [134]:
matrix_product = A @ B
elementwise_product = A * B

print("Matrix multiplication (A @ B):\n", matrix_product)
print("\nElement-wise multiplication (A * B):\n", elementwise_product)

Matrix multiplication (A @ B):
 [[19 22]
 [43 50]]

Element-wise multiplication (A * B):
 [[ 5 12]
 [21 32]]


### Quick Check

Why are `A @ B` and `A * B` different?

- `@` → matrix multiplication
- `*` → element-wise multiplication

## 5. Matrix Transpose

The transpose changes rows into columns.

$
A^T =
\begin{bmatrix}
1 & 3 \\
2 & 4
\end{bmatrix}
$

In NumPy:

```python
A.T
```

In [138]:
print("A =\n", A)
print("\nTranspose of A =\n", A.T)

A =
 [[1 2]
 [3 4]]

Transpose of A =
 [[1 3]
 [2 4]]


## 6. Combining Matrix Operations

Let's calculate:

$
C = A^T B
$

In [141]:
C = A.T @ B
print("A.T @ B =\n", C)

A.T @ B =
 [[26 30]
 [38 44]]


## 7. Eigenvalues and Eigenvectors

For a square matrix \(A\), an eigenvector \(v\) and eigenvalue \(\lambda\) satisfy:

$
Av = \lambda v
$

In this lab we use NumPy's `np.linalg.eig()`.

For a 2×2 matrix:

```python
eigenvalues, eigenvectors = np.linalg.eig(A)
```

Each **column** of `eigenvectors` corresponds to the eigenvalue at the same position in `eigenvalues`.

In [144]:
A = np.array([[4, 1],
              [2, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:\n", A)
print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors (columns):")
print(eigenvectors)

Matrix A:
 [[4 1]
 [2 3]]

Eigenvalues:
[5. 2.]

Eigenvectors (columns):
[[ 0.707 -0.447]
 [ 0.707  0.894]]


## 8. Verify an Eigenpair

Instead of only trusting the function output, verify:

$
Av \approx \lambda v
$

The result may be approximately equal because of floating-point arithmetic.

In [147]:
for i in range(len(eigenvalues)):
    lam = eigenvalues[i]
    v = eigenvectors[:, i]

    left = A @ v
    right = lam * v

    print(f"Eigenpair {i+1}")
    print("A @ v       =", left)
    print("lambda * v   =", right)
    print("Verified     =", np.allclose(left, right))
    print()

Eigenpair 1
A @ v       = [3.536 3.536]
lambda * v   = [3.536 3.536]
Verified     = True

Eigenpair 2
A @ v       = [-0.894  1.789]
lambda * v   = [-0.894  1.789]
Verified     = True



## 9. Eigenvalues of a Simple 2×2 Matrix

Try:

$
A =
\begin{bmatrix}
2 & 0 \\
0 & 3
\end{bmatrix}
$

Predict the eigenvalues before running the code.

In [150]:
A_simple = np.array([[2, 0],
                     [0, 3]])

vals, vecs = np.linalg.eig(A_simple)

print("Eigenvalues:", vals)
print("Eigenvectors:\n", vecs)

Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


## 10. Mini Practice Problem

Given:

$
A =
\begin{bmatrix}
5 & 2 \\
2 & 5
\end{bmatrix}
$

Perform the following:

1. Calculate $A^T$
2. Calculate $A^2 = A @ A$
3. Find eigenvalues and eigenvectors
4. Verify at least one eigenpair using $Av = \lambda v$

In [153]:
# Student practice
A = np.array([[5, 2],
              [2, 5]])

print("Transpose:\n", A.T)
print("\nA squared:\n", A @ A)

vals, vecs = np.linalg.eig(A)
print("\nEigenvalues:", vals)
print("\nEigenvectors:\n", vecs)

# Verify the first eigenpair
v = vecs[:, 0]
lam = vals[0]

print("\nVerification:")
print("A @ v     =", A @ v)
print("lambda * v =", lam * v)
print("Correct?  =", np.allclose(A @ v, lam * v))

Transpose:
 [[5 2]
 [2 5]]

A squared:
 [[29 20]
 [20 29]]

Eigenvalues: [7. 3.]

Eigenvectors:
 [[ 0.707 -0.707]
 [ 0.707  0.707]]

Verification:
A @ v     = [4.95 4.95]
lambda * v = [4.95 4.95]
Correct?  = True


## 11. Lab Challenge

Create a random 2×2 integer matrix using:

```python
np.random.randint()
```

Then:

- calculate its transpose,
- calculate its matrix square,
- find eigenvalues/eigenvectors,
- verify every eigenpair.

**Note:** Some random matrices may have complex eigenvalues. NumPy can represent complex numbers automatically.

In [156]:
rng = np.random.default_rng(42)
R = rng.integers(1, 6, size=(2, 2))

print("Random matrix:\n", R)
print("\nTranspose:\n", R.T)
print("\nR squared:\n", R @ R)

vals, vecs = np.linalg.eig(R)
print("\nEigenvalues:", vals)
print("\nEigenvectors:\n", vecs)

for i, lam in enumerate(vals):
    v = vecs[:, i]
    print(f"Eigenpair {i+1} verified:", np.allclose(R @ v, lam * v))

Random matrix:
 [[1 4]
 [4 3]]

Transpose:
 [[1 4]
 [4 3]]

R squared:
 [[17 16]
 [16 25]]

Eigenvalues: [-2.123  6.123]

Eigenvectors:
 [[-0.788 -0.615]
 [ 0.615 -0.788]]
Eigenpair 1 verified: True
Eigenpair 2 verified: True


## 12. Summary

### NumPy operations used

| Task | NumPy syntax |
|---|---|
| Matrix addition | `A + B` |
| Matrix multiplication | `A @ B` |
| Element-wise multiplication | `A * B` |
| Transpose | `A.T` |
| Eigenvalues/eigenvectors | `np.linalg.eig(A)` |

### Reason why we learn this

Linear algebra is a fundamental aspect of machine learning; it serves as a core technique. In this context, matrices represent both data and model parameters, while eigenvalues and eigenvectors hold particular significance in Principal Component Analysis (PCA), which is covered in Module 2.